### ISSUE TITLE
Is there anything wrong with function getMocularity?

### ISSUE THREAD

**Issue by elifzeng** [TanemuraKiyoto/AutoGraph#2]
In your code:
```
Q += sigma_in / two_m - resolution * (sigma_tot / (2 * two_m)) ** 2
```
According to the paper:
![image](https://user-images.githubusercontent.com/52747634/160117348-b24e3a21-3088-45c4-bfd9-938a84708252.png)

So I think the code should be like:
```python
# no 2 multiply
Q += sigma_in / two_m - resolution * (sigma_tot / two_m) ** 2
```
Should this be modified? Thanks.

**Comment by TanemuraKiyoto** [comment]
Hello elifzeng,

Thank you for catching this item. I have updated the code for calculating the Modularity.
